### ISSUE TITLE
Not working for view using autolayout

### ISSUE THREAD

**Issue by bumaociyuan** [pres/PREBorderView#4]
Hi @pres.

Cuz
`PREBorderView` is using frame
```
CALayer *border = [CALayer layer];
    switch (position) {
        case PREBorderPositionTop:
            border.frame = CGRectMake(0, 0, self.frame.size.width, lineWidth);
            break;
```
when view resize frame or autolayout resize ,,the border will display incorrectly

**Comment by pres** [comment]
Borders are currently not automatically resized.
You need to update the border by setting it after the view has changed its size.

You can just call one of the add border methods again, the previous border will be removed and replaced by the new one.

**Comment by pres** [comment]
`3.1.0` adds functionality to easily update all borders to frame changes.

To easily update all borders to size changes of views use
- Use `layoutBorders` to update borders of a view.
- Use `layoutSubviewBorders` to update borders of a view, as well as all borders of subviews.

To update a controller's view to auto layout changes call `layoutSubviewBorders` in `viewDidLayoutSubviews`.
